name: Dependabot Auto-Merge

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.base_ref == 'main'

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests
      - name: Run tests
        run: npm test

      # Wait for Vercel preview deployment
      - name: Wait for Vercel Deployment
        uses: samuelmeuli/wait-for-vercel-preview@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          deployment-url: "https://patreon-clone-git-${{ github.head_ref }}-*-.rxshabns-projects.vercel.app"
          timeout: 300 # Wait up to 5 minutes for deployment

  auto-merge:
    needs: test-and-validate
    runs-on: ubuntu-latest
    if: success() && github.actor == 'dependabot[bot]'

    steps:
      # Auto-merge the PR if all checks passed
      - name: Auto-merge Dependabot PR
        uses: actions/github-script@v6
        with:
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            })

  notify-failure:
    needs: test-and-validate
    runs-on: ubuntu-latest
    if: failure() && github.actor == 'dependabot[bot]'

    steps:
      - name: Notify Failure
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "⚠️ Dependency update PR failed. Check the logs for more details."
            })
